import type { Metadata } from "next";
import Link from "next/link";

import { absoluteUrl } from "../../lib/site";

export const metadata: Metadata = {
  title: "StreamCanvas Docs",
  description:
    "Quickstart, architecture, deployment, and API guidance for building generative UI apps with StreamCanvas.",
  alternates: {
    canonical: "/docs",
  },
  openGraph: {
    title: "StreamCanvas Docs",
    description:
      "Quickstart, architecture, deployment, and API guidance for StreamCanvas.",
    url: absoluteUrl("/docs"),
  },
};

const sections = [
  {
    body: "Install dependencies, start the reference app, then open the demo thread to see widget streaming and host callbacks.",
    title: "Quickstart",
  },
  {
    body: "Use @streamcanvas/core for the stream contract, @streamcanvas/react for the UI primitives, and @streamcanvas/server for reference runtime helpers.",
    title: "Architecture",
  },
  {
    body: "Deploy behind nginx with a localhost-bound Docker container so the app stays isolated from existing services on the host.",
    title: "Deployment",
  },
];

export default function DocsPage() {
  return (
    <main className="shell docs-shell">
      <header className="site-nav">
        <Link className="brand" href="/">
          StreamCanvas
        </Link>
        <nav className="nav-links">
          <Link href="/">Overview</Link>
          <Link href="/demo">Demo</Link>
          <a href="https://github.com/miounet11/claude-generative-ui">GitHub</a>
        </nav>
      </header>

      <section className="docs-hero">
        <div className="eyebrow">Documentation</div>
        <h1 className="hero-title small">Run it locally. Deploy it safely. Extend it sanely.</h1>
        <p className="hero-copy">
          StreamCanvas ships as a reference app plus reusable packages. This page is
          the fastest path from clone to working generative UI.
        </p>
      </section>

      <section className="section-grid">
        {sections.map((section) => (
          <article className="section-card" key={section.title}>
            <div className="section-kicker">Guide</div>
            <h2>{section.title}</h2>
            <p>{section.body}</p>
          </article>
        ))}
      </section>

      <section className="docs-grid">
        <article className="docs-card">
          <div className="section-kicker">Install</div>
          <pre className="code-panel">{`pnpm install
pnpm dev`}</pre>
          <p className="docs-copy">
            Open <strong>http://localhost:3000</strong> and use the demo prompts to
            verify message streaming, widget rendering, and client tool callbacks.
          </p>
        </article>

        <article className="docs-card">
          <div className="section-kicker">Use the packages</div>
          <pre className="code-panel">{`import {
  StreamCanvasProvider,
  ChatThread,
  WidgetSurface,
} from "@streamcanvas/react";`}</pre>
          <p className="docs-copy">
            The React package expects the same NDJSON event stream generated by the
            server helpers or your own backend implementation.
          </p>
        </article>

        <article className="docs-card">
          <div className="section-kicker">Deploy</div>
          <pre className="code-panel">{`docker compose -f infra/docker-compose.yml up -d --build
cp infra/nginx/codeclaude.cn.conf /etc/nginx/conf.d/codeclaude.cn.conf
nginx -t && systemctl reload nginx`}</pre>
          <p className="docs-copy">
            The container binds to <strong>127.0.0.1:3210</strong> only, so nginx
            can route traffic without conflicting with existing public services.
          </p>
        </article>
      </section>

      <section className="docs-grid two-up">
        <article className="docs-card">
          <div className="section-kicker">Scaffold</div>
          <pre className="code-panel">{`npx create-streamcanvas my-app
cd my-app
pnpm install
pnpm dev`}</pre>
        </article>

        <article className="docs-card">
          <div className="section-kicker">Public routes</div>
          <ul className="docs-list">
            <li>`/` marketing landing page</li>
            <li>`/demo` live product demo</li>
            <li>`/docs` onboarding and integration notes</li>
            <li>`/api/health` deployment health probe</li>
            <li>`/api/demo` NDJSON demo stream endpoint</li>
          </ul>
        </article>
      </section>
    </main>
  );
}
