import type { Metadata } from "next";
import Link from "next/link";

import { SiteFooter } from "../../components/site-footer";
import { SiteHeader } from "../../components/site-header";
import { createLocaleAlternates } from "../../lib/locales";
import { absoluteUrl } from "../../lib/site";

export const metadata: Metadata = {
  title: "StreamCanvas Docs",
  description:
    "Quickstart, architecture, deployment, and API guidance for building generative UI apps with StreamCanvas.",
  alternates: createLocaleAlternates("/docs"),
  openGraph: {
    title: "StreamCanvas Docs",
    description:
      "Quickstart, architecture, deployment, and API guidance for StreamCanvas.",
    url: absoluteUrl("/docs"),
  },
};

const sections = [
  {
    body: "Install dependencies, start the reference app, then open the demo thread to see widget streaming and host callbacks.",
    title: "Quickstart",
  },
  {
    body: "Use @streamcanvas/core for the stream contract, @streamcanvas/react for the UI primitives, and @streamcanvas/server for reference runtime helpers.",
    title: "Architecture",
  },
  {
    body: "Deploy behind nginx with a localhost-bound Docker container so the app stays isolated from existing services on the host.",
    title: "Deployment",
  },
];

export default function DocsPage() {
  return (
    <main className="shell docs-shell">
      <SiteHeader currentPath="/docs" locale="en" />

      <section className="docs-hero">
        <div className="eyebrow">Documentation</div>
        <h1 className="hero-title small">Run it locally. Deploy it safely. Extend it sanely.</h1>
        <p className="hero-copy">
          StreamCanvas ships as a reference app plus reusable packages. This page is
          the fastest path from clone to working generative UI.
        </p>
      </section>

      <section className="section-grid">
        {sections.map((section) => (
          <article className="section-card" key={section.title}>
            <div className="section-kicker">Guide</div>
            <h2>{section.title}</h2>
            <p>{section.body}</p>
          </article>
        ))}
      </section>

      <section className="docs-grid">
        <article className="docs-card">
          <div className="section-kicker">Install</div>
          <pre className="code-panel">{`pnpm install
pnpm dev`}</pre>
          <p className="docs-copy">
            Open <strong>http://localhost:3000</strong> and use the demo prompts to
            verify message streaming, widget rendering, and client tool callbacks.
          </p>
        </article>

        <article className="docs-card">
          <div className="section-kicker">Use the packages</div>
          <pre className="code-panel">{`import {
  StreamCanvasProvider,
  ChatThread,
  WidgetSurface,
} from "@streamcanvas/react";`}</pre>
          <p className="docs-copy">
            The React package expects the same NDJSON event stream generated by the
            server helpers or your own backend implementation.
          </p>
        </article>

        <article className="docs-card">
          <div className="section-kicker">Deploy</div>
          <pre className="code-panel">{`pnpm build
rsync -az apps/web/.next/standalone/ server:/opt/streamcanvas-web/
rsync -az apps/web/.next/static/ server:/opt/streamcanvas-web/apps/web/.next/static/
systemctl enable --now streamcanvas-web`}</pre>
          <p className="docs-copy">
            The preferred production path uses the Next.js standalone runtime behind
            nginx with the app bound only to <strong>127.0.0.1:3210</strong>.
          </p>
        </article>
      </section>

      <section className="docs-grid two-up">
        <article className="docs-card">
          <div className="section-kicker">Scaffold</div>
          <pre className="code-panel">{`npx create-streamcanvas my-app
cd my-app
pnpm install
pnpm dev`}</pre>
        </article>

        <article className="docs-card">
          <div className="section-kicker">Public routes</div>
          <ul className="docs-list">
            <li><code>/</code> marketing landing page</li>
            <li><code>/platform</code> architecture and deployment model</li>
            <li><code>/solutions</code> product-fit and workflow examples</li>
            <li><code>/security</code> safety and operational boundaries</li>
            <li><code>/resources</code> professional long-form content hub</li>
            <li><code>/claude-generative-ui</code> intent page for Claude-style OSS discovery</li>
            <li><code>/demo</code> live product demo</li>
            <li><code>/api/health</code> deployment health probe</li>
            <li><code>/api/demo</code> NDJSON demo stream endpoint</li>
          </ul>
        </article>
      </section>

      <SiteFooter locale="en" />
    </main>
  );
}
